// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"JobParamAdjust","status":true,"description":"アクターごとのベース能力に職業ごとの補正をかけて成長させるシステムを実装します。職業変更してもベースは保持されます。","parameters":{}},
{"name":"JobProficiency","status":true,"description":"敵撃破時に熟練度ポイントをプラグイン内に蓄積し、勝利時にまとめてアクターの熟練度に加算するプラグインです。","parameters":{}},
{"name":"ClassNameEscape","status":true,"description":"職業IDに対応する職業名を \\J[n] で表示（選択肢でも使えます）[Ver.1.3]","parameters":{}},
{"name":"EquipRefine","status":true,"description":"Ver.1.2 - 装備（武器・防具）をスロットID + アイテムIDで管理し強化レベルを保持・表示するプラグイン（セーブ対応）","parameters":{}},
{"name":"ShowJobProficiencyAll","status":true,"description":"アクター1～4の現在の熟練度をシンプルに表示するプラグイン [ver 1.0]","parameters":{}}
];
